EcmMobileShop/EcmMobileShop/Areas/OneTechAdmin/Controllers/HomeAdminController.cs
using EcmMobileShop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcmMobileShop.Areas.OneTechAdmin.Controllers
{
    public class HomeAdminController : Controller
    {
        private EcmMobileShopEntities ecmMobile = new EcmMobileShopEntities();
        [Authorize(Roles = "Admin")]
        // GET: OneTechAdmin/Home
        public ActionResult Index()
        {
            var topSellingProducts = ecmMobile.tb_SANPHAM
                         .Join(ecmMobile.tb_CHITIETHOADON,
                               sp => sp.IdSP,
                               cthd => cthd.tb_CT_SANPHAM.IdSP,
                               (sp, cthd) => new { sp, cthd })
                         .GroupBy(x => new { x.sp.IdSP, x.sp.TenSP })
                         .Select(g => new {
                             TenSanPham = g.Key.TenSP,
                             SoLuongBan = g.Sum(x => x.cthd.SoLuongBan),
                             TongTienBan = g.Sum(x => x.cthd.SoLuongBan * x.cthd.GiaBan)
                         })
                         .OrderByDescending(x => x.SoLuongBan)
                         .Take(5)
                         .ToList();



            var modelCollection = new ModelCollection();
            modelCollection.AddModel(topSellingProducts);
            
            return View();
        }

        [Authorize(Roles = "Admin")]
        public ActionResult getDataNamNay()
        {
           
                double[] data = new double[12];

            // Lấy danh sách đơn hàng mới từ cơ sở dữ liệu
            var orders = ecmMobile.tb_HOADON
                         .Where(hd => hd.NgayLap != null && hd.NgayLap.Value.Year == DateTime.Now.Year)
                         .ToList();


            // Tính doanh số bán được của từng tháng
            foreach (var order in orders)
                {
                // Tính tổng số tiền bán được của hoá đơn đó
                double total = ecmMobile.tb_CHITIETHOADON
                                .Where(cthd => cthd.IdHD == order.IdHD)
                                .Sum(cthd => cthd.SoLuongBan * cthd.GiaBan)
                                .GetValueOrDefault();


                // Lấy tháng của Ngaylap trong hoá đơn
                int month = order.NgayLap.HasValue ? order.NgayLap.Value.Month : 0;

                // Tính tổng doanh số của tháng đó
                data[month - 1] += total;
                }

                string arrayString = "var dataNamNay = [" + string.Join(",", data) + "];";

                return Content(arrayString);

        }
        [Authorize(Roles = "Admin")]
        public ActionResult getDoanhThu()
        {
            double Tong = 0;

            // Lấy danh sách đơn hàng mới từ cơ sở dữ liệu
            var orders = ecmMobile.tb_HOADON
                         .Where(hd => hd.NgayLap != null)
                         .ToList();

            // Tính doanh số bán được của từng đơn hàng
            foreach (var order in orders)
            {
                // Tính tổng số tiền bán được của hoá đơn đó
                double total = ecmMobile.tb_CHITIETHOADON
                                .Where(cthd => cthd.IdHD == order.IdHD)
                                .Sum(cthd => cthd.SoLuongBan * cthd.GiaBan)
                                .GetValueOrDefault();

                // Cộng tổng doanh thu bán được của đơn hàng đó vào biến Tong
                Tong += total;
            }

            return Content(Tong.ToString());
        }


        [Authorize(Roles = "Admin")]
        public ActionResult getPhanTramDoanhSo()
        {
            // Lấy doanh thu của tháng này
            double doanhThuThangNay = ecmMobile.tb_CHITIETHOADON
            .Where(cthd => cthd.tb_HOADON.NgayLap != null && cthd.tb_HOADON.NgayLap.Value.Year == DateTime.Now.Year && cthd.tb_HOADON.NgayLap.Value.Month == DateTime.Now.Month)
            .Sum(cthd => cthd.SoLuongBan * cthd.GiaBan)
            .GetValueOrDefault();
            // Lấy doanh thu của tháng trước
            DateTime thangTruoc = DateTime.Now.AddMonths(-1);
            double doanhThuThangTruoc = ecmMobile.tb_CHITIETHOADON
                                         .Where(cthd => cthd.tb_HOADON.NgayLap != null && cthd.tb_HOADON.NgayLap.Value.Year == thangTruoc.Year && cthd.tb_HOADON.NgayLap.Value.Month == thangTruoc.Month)
                                         .Sum(cthd => cthd.SoLuongBan * cthd.GiaBan)
                                         .GetValueOrDefault();

            if(doanhThuThangTruoc == 0)
            {
                return Content("100");
            }    
            // Tính phần trăm tăng/giảm so với tháng trước
            double phanTram = (doanhThuThangNay - doanhThuThangTruoc) / doanhThuThangTruoc * 100;

            return Content(phanTram.ToString());
        }





            [Authorize(Roles = "Admin")]
        public ActionResult getDataNamTruoc()
        {
            double[] data = new double[12];

            // Lấy danh sách đơn hàng mới từ cơ sở dữ liệu
            var orders = ecmMobile.tb_HOADON
                         .Where(hd => hd.NgayLap != null && hd.NgayLap.Value.Year == DateTime.Now.Year - 1)
                         .ToList();


            // Tính doanh số bán được của từng tháng
            foreach (var order in orders)
            {
                // Tính tổng số tiền bán được của hoá đơn đó
                double total = ecmMobile.tb_CHITIETHOADON
                                .Where(cthd => cthd.IdHD == order.IdHD)
                                .Sum(cthd => cthd.SoLuongBan * cthd.GiaBan)
                                .GetValueOrDefault();


                // Lấy tháng của Ngaylap trong hoá đơn
                int month = order.NgayLap.HasValue ? order.NgayLap.Value.Month : 0;

                // Tính tổng doanh số của tháng đó
                data[month - 1] += total;
            }

            string arrayString = "var dataNamTruoc = [" + string.Join(",", data) + "];";

            return Content(arrayString);
        }




    }
}

EcmMobileShop/EcmMobileShop/Areas/OneTechAdmin/Views/HomeAdmin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/OneTechAdmin/Views/Shared/_layoutAdmin.cshtml";
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 col-6">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner">
                        <h3>
                            @{
                                Html.RenderAction("GetNewOrders", "OrderAdmin");
                            }
                        </h3>

                        <p>Đơn hàng mới</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="@Url.Action("Index", "OrderAdmin", new { area = "OneTechAdmin" })" class="small-box-footer">Xem chi tiết <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->

            <div class="col-lg-6 col-6">
                <!-- small box -->
                <div class="small-box bg-warning">
                    <div class="inner">
                        <h3>
                            @{
                                Html.RenderAction("GetUser", "tKHACHHANG");
                            }
                        </h3>

                        <p>Khách hàng đăng ký</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="@Url.Action("Index", "tKHACHHANG", new { area = "OneTechAdmin" })" class="small-box-footer">Xem chi tiết <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>
            <!-- ./col -->

        </div>

        <div class="row">

            <!-- /.col-md-6 -->
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="d-flex justify-content-between">
                            <h3 class="card-title">Doanh số</h3>
                            <a href="@Url.Action("Index", "ReportDT", new { area = "OneTechAdmin" })">Xem báo cáo</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="d-flex">
                            <p class="d-flex flex-column">
                                <span class="text-bold text-lg">
                                    $@{
                                        Html.RenderAction("getDoanhThu", "HomeAdmin");
                                    }
                                </span>
                                <span>Toàn bộ thời gian</span>
                            </p>
                            <p class="ml-auto d-flex flex-column text-right">
                                <span class="text-success">
                                    <i class="fas fa-arrow-up"></i> @{
                                        Html.RenderAction("getPhanTramDoanhSo", "HomeAdmin");
                                    }%
                                </span>
                                <span class="text-muted">Tháng trước</span>
                            </p>
                        </div>
                        <!-- /.d-flex -->

                        <div class="position-relative mb-4">
                            <canvas id="sales-chart" height="200"></canvas>
                        </div>

                        <div class="d-flex flex-row justify-content-end">
                            <span class="mr-2">
                                <i class="fas fa-square text-primary"></i> Năm nay
                            </span>

                            <span>
                                <i class="fas fa-square text-gray"></i> Năm nay
                            </span>
                        </div>
                    </div>
                </div>
                <!-- /.card -->       
                
            </div>
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header border-0">
                        <h3 class="card-title">Products</h3>
                        <div class="card-tools">
                            <a href="#" class="btn btn-tool btn-sm">
                                <i class="fas fa-download"></i>
                            </a>
                            <a href="#" class="btn btn-tool btn-sm">
                                <i class="fas fa-bars"></i>
                            </a>
                        </div>
                    </div>
                    <div class="card-body table-responsive p-0">
                        <table class="table table-striped table-valign-middle">
                            <thead>
                                <tr>
                                    <th>Sản phẩm</th>
                                    <th>Giá</th>
                                    <th>Doanh số</th>
                                    <th>Thông tin chi tiết</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                <tr>
                                    <td>

                                        Some Product
                                    </td>
                                    <td>$13 USD</td>
                                    <td>
                                        <small class="text-success mr-1">
                                            <i class="fas fa-arrow-up"></i>
                                            12%
                                        </small>
                                        12,000 Sold
                                    </td>
                                    <td>
                                        <a href="#" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>

                                        Another Product
                                    </td>
                                    <td>$29 USD</td>
                                    <td>
                                        <small class="text-warning mr-1">
                                            <i class="fas fa-arrow-down"></i>
                                            0.5%
                                        </small>
                                        123,234 Sold
                                    </td>
                                    <td>
                                        <a href="#" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>

                                        Amazing Product
                                    </td>
                                    <td>$1,230 USD</td>
                                    <td>
                                        <small class="text-danger mr-1">
                                            <i class="fas fa-arrow-down"></i>
                                            3%
                                        </small>
                                        198 Sold
                                    </td>
                                    <td>
                                        <a href="#" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>

                                        Perfect Item
                                        <span class="badge bg-danger">NEW</span>
                                    </td>
                                    <td>$199 USD</td>
                                    <td>
                                        <small class="text-success mr-1">
                                            <i class="fas fa-arrow-up"></i>
                                            63%
                                        </small>
                                        87 Sold
                                    </td>
                                    <td>
                                        <a href="#" class="text-muted">
                                            <i class="fas fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-md-6 -->

        </div>
    </div>
</div>


        